---
- hosts: dev
  become: True
  tasks:
    - name: update
      apt:
        name: apt-get update
        state: present
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: krusapss
        image: "krushang007/krusapss:0.2"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
